#!/bin/bash

# Check if the r0ket folder variable is set
if [ ! -n "$R0KET" ]; then
  R0KET="$HOME/r0ket"
fi

DIRECTORY=$PWD

echo "Copying snake.c to $R0KET/firmware/l0dable"
cp snake_sp.c "$R0KET/firmware/l0dable"
cp snake_host.c "$R0KET/firmware/l0dable"
cp snake_client.c "$R0KET/firmware/l0dable"
cp snake_shared.c "$R0KET/firmware/l0dable"

cd "$R0KET/firmware/l0dable"

echo "Building..."
echo SINGLE PLAYER
echo
make snake_sp.c0d && mv snake_sp.c0d $DIRECTORY
echo
echo HOST
echo 
make snake_host.c0d && mv snake_host.c0d $DIRECTORY
echo
echo CLIENT
echo
make snake_client.c0d && mv snake_client.c0d $DIRECTORY
cd $DIRECTORY

echo "Finished."
