#!/bin/bash

# Check if the r0ket folder variable is set
if [ ! -n "$R0KET" ]; then
  R0KET="$HOME/r0ket"
fi

DIRECTORY=$PWD

echo "Copying snake.c to $R0KET/firmware/l0dable"
cp snake_sp.c "$R0KET/firmware/l0dable"
cp snakesrv.c "$R0KET/firmware/l0dable"
cp snakecli.c "$R0KET/firmware/l0dable"
cp snakeno.c "$R0KET/firmware/l0dable"
cp snake_shared.c "$R0KET/firmware/l0dable"

cd "$R0KET/firmware/l0dable"

echo "Building..."
echo SINGLE PLAYER
echo
make snake_sp.c0d && mv snake_sp.c0d $DIRECTORY
echo
echo HOST
echo 
make snakesrv.c0d && mv snakesrv.c0d $DIRECTORY
echo
echo CLIENT
echo
make snakecli.c0d && mv snakecli.c0d $DIRECTORY
echo
echo CHAT CLIENT
echo
make snakeno.c0d && mv snakeno.c0d $DIRECTORY
cd $DIRECTORY

echo "Finished."
